// flow-typed signature: 6b6318b85cdf41a159858d704eb8a393
// flow-typed version: <<STUB>>/ric_v^1.3.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ric'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ric' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ric/src/ric-polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ric/src/ric-polyfill.js' {
  declare module.exports: $Exports<'ric/src/ric-polyfill'>;
}
