// flow-typed signature: a9a0bde3d021a88469b9ce7e58b76647
// flow-typed version: <<STUB>>/stream-combiner2_v^1.1.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-combiner2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-combiner2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-combiner2/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-combiner2/index' {
  declare module.exports: $Exports<'stream-combiner2'>;
}
declare module 'stream-combiner2/index.js' {
  declare module.exports: $Exports<'stream-combiner2'>;
}
declare module 'stream-combiner2/test/index.js' {
  declare module.exports: $Exports<'stream-combiner2/test/index'>;
}
